export function toVariableName(filePath: string, includeExt = false): string {
  // Strip leading 'assets/' prefix
  const withoutPrefix = filePath.startsWith('assets/')
    ? filePath.slice('assets/'.length)
    : filePath;
  // Extract extension (without the dot)
  const extMatch = withoutPrefix.match(/\.([^/.]+)$/);
  const ext = extMatch ? extMatch[1] : '';
  const withoutExt = withoutPrefix.replace(/\.[^/.]+$/, '');
  // Optionally append extension as a name segment
  const source = includeExt && ext ? `${withoutExt}_${ext}` : withoutExt;
  // Split on path separators and word separators
  const words = source.split(/[/\-_.\s]+/).filter(Boolean);
  // camelCase: first word all lowercase, subsequent words capitalize first char
  const camel = words
    .map((w, i) => (i === 0 ? w.toLowerCase() : w.charAt(0).toUpperCase() + w.slice(1)))
    .join('');
  // Prefix 'a' if result starts with a digit
  return /^\d/.test(camel) ? 'a' + camel : camel;
}

export function generateDartCode(className = 'Assets', assets: string[]): string {
  // Deduplicate paths — guard against scanner returning the same path twice
  const uniqueAssets = [...new Set(assets)];

  // First pass: detect which base names (without ext) have collisions
  const baseCounts = new Map<string, number>();
  for (const assetPath of uniqueAssets) {
    const base = toVariableName(assetPath, false);
    baseCounts.set(base, (baseCounts.get(base) ?? 0) + 1);
  }

  const seen = new Map<string, number>();
  const lines: string[] = [
    '// GENERATED CODE - DO NOT MODIFY BY HAND',
    '// Generated by Flutter Generate Assets VSCode Extension',
    '// https://github.com/ceeyang/flutter_generate_assets',
    '// ignore_for_file: lines_longer_than_80_chars, constant_identifier_names',
    '// dart format off',
    `class ${className} {`,
  ];

  for (const assetPath of uniqueAssets) {
    const base = toVariableName(assetPath, false);
    // Use extension in name only when there's a collision on the base name
    const useExt = (baseCounts.get(base) ?? 1) > 1;
    let varName = toVariableName(assetPath, useExt);
    // Fallback numeric suffix for any remaining collisions (e.g. identical paths)
    if (seen.has(varName)) {
      let count = seen.get(varName)! + 1;
      let candidate = varName + count;
      while (seen.has(candidate)) { count++; candidate = varName + count; }
      seen.set(varName, count);
      seen.set(candidate, 1);
      varName = candidate;
    } else {
      seen.set(varName, 1);
    }
    lines.push(`  static const String ${varName} = '${assetPath}';`);
  }

  lines.push('}');
  return lines.join('\n') + '\n';
}
